### ISSUE TITLE
Treemap back button does not work

### ISSUE THREAD

**Issue by drvillamizar** [d3plus/d3plus#720] opened 2021-09-02 03:59 UTC
Hi!! I have a problem! i'm using d3plus v 2.0 (https://cdn.jsdelivr.net/npm/d3plus@2) 
![treemap_bug](https://user-images.githubusercontent.com/23440680/131779686-e9c314d9-9d9d-4ef5-bad0-0abfd7d844db.png)
and Treemap with drilldown data - back button break the chart
do you know how this can be avoided?
Thanks!!

 
cc @davelandry

**Comment by davelandry** [comment] 2021-09-07 12:43
Closing as a duplicate of #701

**Closed by davelandry** 2021-09-07 12:43 UTC
